# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitLossRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom Period')], help_text='Type of period for this calculation', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the period')),
                ('end_date', models.DateField(help_text='End date of the period')),
                ('total_sales_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total income from sales.grand_total', max_digits=15)),
                ('total_cost_of_goods_sold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of goods sold in this period', max_digits=15)),
                ('total_labor_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payments to labor', max_digits=15)),
                ('total_vendor_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payments to vendors', max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total expenses amount', max_digits=15)),
                ('total_zakat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total zakat amount', max_digits=15)),
                ('total_expenses_calculated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total expenses (labor + vendor + other + zakat)', max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit (income - cost of goods sold)', max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net profit (gross profit - total expenses)', max_digits=15)),
                ('gross_profit_margin_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit margin as percentage of sales', max_digits=5)),
                ('profit_margin_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net profit margin as percentage of sales', max_digits=5)),
                ('total_products_sold', models.PositiveIntegerField(default=0, help_text='Total number of products sold in this period')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average order value in this period', max_digits=12)),
                ('calculation_notes', models.TextField(blank=True, help_text='Notes about the calculation or any adjustments')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profit_loss_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profit & Loss Record',
                'verbose_name_plural': 'Profit & Loss Records',
                'db_table': 'profit_loss_record',
                'ordering': ['-start_date', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitLossCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_type', models.CharField(choices=[('SALES_INCOME', 'Sales Income'), ('LABOR_PAYMENTS', 'Labor Payments'), ('VENDOR_PAYMENTS', 'Vendor Payments'), ('EXPENSES', 'Other Expenses'), ('ZAKAT', 'Zakat'), ('PROFIT_CALCULATION', 'Profit Calculation')], help_text='Type of calculation performed', max_length=20)),
                ('source_model', models.CharField(help_text="Source model for the calculation (e.g., 'Sales', 'Payment')", max_length=50)),
                ('source_count', models.PositiveIntegerField(default=0, help_text='Number of source records used in calculation')),
                ('source_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount from source records', max_digits=15)),
                ('calculation_details', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of the calculation')),
                ('calculation_notes', models.TextField(blank=True, help_text='Notes about this specific calculation')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this calculation was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profit_loss_record', models.ForeignKey(help_text='Associated profit and loss record', on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='profit_loss.profitlossrecord')),
            ],
            options={
                'verbose_name': 'Profit & Loss Calculation',
                'verbose_name_plural': 'Profit & Loss Calculations',
                'db_table': 'profit_loss_calculation',
                'ordering': ['profit_loss_record', 'calculation_type', 'calculated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='profitlossrecord',
            index=models.Index(fields=['period_type'], name='profit_loss_period__c24370_idx'),
        ),
        migrations.AddIndex(
            model_name='profitlossrecord',
            index=models.Index(fields=['start_date', 'end_date'], name='profit_loss_start_d_4c9b45_idx'),
        ),
        migrations.AddIndex(
            model_name='profitlossrecord',
            index=models.Index(fields=['is_active'], name='profit_loss_is_acti_429c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='profitlossrecord',
            index=models.Index(fields=['created_at'], name='profit_loss_created_f02226_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profitlossrecord',
            unique_together={('period_type', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='profitlosscalculation',
            index=models.Index(fields=['profit_loss_record'], name='profit_loss_profit__e05bed_idx'),
        ),
        migrations.AddIndex(
            model_name='profitlosscalculation',
            index=models.Index(fields=['calculation_type'], name='profit_loss_calcula_d4e9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='profitlosscalculation',
            index=models.Index(fields=['source_model'], name='profit_loss_source__0118ac_idx'),
        ),
        migrations.AddIndex(
            model_name='profitlosscalculation',
            index=models.Index(fields=['calculated_at'], name='profit_loss_calcula_ddea2a_idx'),
        ),
    ]
