# Generated by Django 6.0.1 on 2026-01-28 12:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitlossrecord',
            name='average_order_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average order value in this period', max_digits=15),
        ),
        migrations.AlterField(
            model_name='profitlossrecord',
            name='gross_profit_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit margin as percentage of sales', max_digits=8),
        ),
        migrations.AlterField(
            model_name='profitlossrecord',
            name='profit_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net profit margin as percentage of sales', max_digits=8),
        ),
    ]
