# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Cached customer name at time of order', max_length=200)),
                ('customer_phone', models.CharField(help_text='Cached customer phone at time of order', max_length=20)),
                ('customer_email', models.EmailField(blank=True, help_text='Cached customer email at time of order', max_length=254)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid in advance', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total order amount (calculated from order items)', max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining amount to be paid', max_digits=15)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Whether the order is fully paid')),
                ('date_ordered', models.DateField(default=django.utils.timezone.now, help_text='Date when order was placed')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('description', models.TextField(blank=True, help_text='Order description and notes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PRODUCTION', 'In Production'), ('READY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current order status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_status', models.CharField(choices=[('NOT_CONVERTED', 'Not Converted'), ('PARTIALLY_CONVERTED', 'Partially Converted'), ('FULLY_CONVERTED', 'Fully Converted')], default='NOT_CONVERTED', help_text='Status of order conversion to sales', max_length=20)),
                ('converted_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount converted to sales', max_digits=15)),
                ('conversion_date', models.DateTimeField(blank=True, help_text='Date when order was first converted to sale', null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ['-date_ordered', '-created_at'],
            },
        ),
    ]
