# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='order_custome_7c3d15_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_35c31c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_ordered'], name='order_date_or_488026_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['expected_delivery_date'], name='order_expecte_008f15_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_active'], name='order_is_acti_427ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_6dbd10_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_fully_paid'], name='order_is_full_38f960_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['conversion_status'], name='order_convers_bc19fd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['conversion_date'], name='order_convers_149d51_idx'),
        ),
    ]
