# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('detail', models.TextField(help_text='Product description/details')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product selling price in PKR', max_digits=12)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Production/purchase cost price in PKR', max_digits=12, null=True)),
                ('color', models.CharField(help_text='Product color', max_length=50)),
                ('fabric', models.CharField(help_text='Fabric type/material', max_length=100)),
                ('pieces', models.JSONField(default=list, help_text="Array of product pieces (e.g., ['Blouse', 'Lehenga', 'Dupatta'])")),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available quantity in stock')),
                ('quantity_available', models.PositiveIntegerField(default=0, help_text='Available quantity excluding reserved stock')),
                ('quantity_reserved', models.PositiveIntegerField(default=0, help_text='Quantity currently reserved for pending sales')),
                ('min_stock_threshold', models.PositiveIntegerField(default=5, help_text='Minimum stock level before low stock warning')),
                ('reorder_point', models.PositiveIntegerField(default=10, help_text='Stock level at which to reorder')),
                ('max_stock_level', models.PositiveIntegerField(default=100, help_text='Maximum stock level to maintain')),
                ('is_active', models.BooleanField(default=True, help_text="Used for soft deletion. Inactive products won't appear in lists")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_quantity', models.PositiveIntegerField(help_text='Quantity before change')),
                ('new_quantity', models.PositiveIntegerField(help_text='Quantity after change')),
                ('change_type', models.CharField(choices=[('SALE_CONFIRMATION', 'Sale Confirmation'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('RESTOCK', 'Restock'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('BULK_UPDATE', 'Bulk Update'), ('SYSTEM_CORRECTION', 'System Correction')], help_text='Type of stock change', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the stock change')),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID (sale, order, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_changes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_changes', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Change Log',
                'verbose_name_plural': 'Stock Change Logs',
                'db_table': 'stock_change_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_id', models.CharField(help_text='ID of the sale this reservation is for', max_length=100)),
                ('quantity_reserved', models.PositiveIntegerField(help_text='Quantity reserved for this sale')),
                ('reserved_until', models.DateTimeField(help_text='When this reservation expires')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether this reservation has been confirmed')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When this reservation was confirmed', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this reservation is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='products.product')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'db_table': 'stock_reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_categor_26b384_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['quantity'], name='product_quantit_e949e8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='product_price_d2c05d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='product_is_acti_916801_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='product_created_fe1f54_idx'),
        ),
        migrations.AddIndex(
            model_name='stockchangelog',
            index=models.Index(fields=['product', 'created_at'], name='stock_chang_product_df5cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockchangelog',
            index=models.Index(fields=['change_type', 'created_at'], name='stock_chang_change__02c709_idx'),
        ),
        migrations.AddIndex(
            model_name='stockchangelog',
            index=models.Index(fields=['changed_by', 'created_at'], name='stock_chang_changed_d52462_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['product', 'is_active'], name='stock_reser_product_09ee21_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['sale_id', 'is_active'], name='stock_reser_sale_id_fbc2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['reserved_until'], name='stock_reser_reserve_28f01f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['is_confirmed'], name='stock_reser_is_conf_14f8cb_idx'),
        ),
    ]
