# Generated by Django 6.0.1 on 2026-01-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_reorder_point'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_reorder_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.PositiveIntegerField(default=10, help_text='Stock level at which to reorder'),
        ),
    ]
