# Generated by Django 6.0.2 on 2026-02-27 01:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_product_reorder_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram (kg)'), ('GM', 'Gram (g)'), ('PC', 'Piece (pc)'), ('PK', 'Pack (pk)'), ('LTR', 'Litre (l)'), ('ML', 'Millilitre (ml)'), ('DZ', 'Dozen (dz)'), ('BOX', 'Box')], default='PC', help_text='Measurement unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Product color (optional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, help_text='Fabric type/material (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_stock_level',
            field=models.DecimalField(decimal_places=3, default=Decimal('100.000'), help_text='Maximum stock level to maintain', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_threshold',
            field=models.DecimalField(decimal_places=3, default=Decimal('5.000'), help_text='Minimum stock level before low stock warning', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces',
            field=models.JSONField(blank=True, default=list, help_text='Array of product pieces (optional)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Available quantity in stock', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Available quantity excluding reserved stock', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity currently reserved for pending sales', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.DecimalField(decimal_places=3, default=Decimal('10.000'), help_text='Stock level at which to reorder', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockchangelog',
            name='new_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity after change', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockchangelog',
            name='old_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity before change', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=3, help_text='Quantity reserved for this sale', max_digits=12),
        ),
    ]
