# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debtor_name', models.CharField(help_text='Name of the person who owes money', max_length=200)),
                ('debtor_phone', models.CharField(help_text='Phone number of the debtor', max_length=20)),
                ('amount_given', models.DecimalField(decimal_places=2, help_text='Amount of money lent to the debtor', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason_or_item', models.TextField(help_text='Reason for lending money or item description')),
                ('date_lent', models.DateField(default=django.utils.timezone.now, help_text='Date when money was lent')),
                ('expected_return_date', models.DateField(blank=True, help_text='Expected date for money return', null=True)),
                ('amount_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of money returned by the debtor', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining amount to be returned', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the receivable')),
                ('is_active', models.BooleanField(default=True, help_text="Used for soft deletion. Inactive receivables won't appear in lists")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this receivable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receivables', to=settings.AUTH_USER_MODEL)),
                ('related_sale', models.ForeignKey(blank=True, help_text='Related sale if this receivable is from a sale transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='sales.sales')),
            ],
            options={
                'verbose_name': 'Receivable',
                'verbose_name_plural': 'Receivables',
                'db_table': 'receivable',
                'ordering': ['-date_lent', '-created_at'],
                'indexes': [models.Index(fields=['debtor_name'], name='receivable_debtor__767013_idx'), models.Index(fields=['debtor_phone'], name='receivable_debtor__d0a5e2_idx'), models.Index(fields=['date_lent'], name='receivable_date_le_447d9b_idx'), models.Index(fields=['expected_return_date'], name='receivable_expecte_24c659_idx'), models.Index(fields=['balance_remaining'], name='receivable_balance_a37889_idx'), models.Index(fields=['is_active'], name='receivable_is_acti_387d26_idx'), models.Index(fields=['created_at'], name='receivable_created_5bdc7d_idx')],
            },
        ),
    ]
