# Generated by Django 6.0.1 on 2026-01-28 11:56

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalAccountBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance', max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_transaction_id', models.UUIDField(blank=True, help_text='ID of the last transaction that updated this balance', null=True)),
            ],
            options={
                'verbose_name': 'Principal Account Balance',
                'verbose_name_plural': 'Principal Account Balances',
                'db_table': 'principal_account_balance',
            },
        ),
        migrations.CreateModel(
            name='PrincipalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, help_text='Transaction date')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Transaction time')),
                ('source_module', models.CharField(choices=[('SALES', 'Sales'), ('ORDERS', 'Orders'), ('PAYMENTS', 'Payments'), ('RECEIVABLES', 'Receivables'), ('PAYABLES', 'Payables'), ('ADVANCE_PAYMENT', 'Advance Payment'), ('EXPENSES', 'Expenses'), ('ZAKAT', 'Zakat'), ('LABOR', 'Labor'), ('VENDOR', 'Vendor'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer')], help_text='Module that generated this transaction', max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='ID of the source record (e.g., sale ID, order ID)', max_length=100, null=True)),
                ('description', models.TextField(help_text='Description of the transaction')),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], help_text='Transaction type (credit/debit)', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=15)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Account balance before this transaction', max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Account balance after this transaction', max_digits=15)),
                ('handled_by', models.CharField(blank=True, help_text='Person who handled this transaction', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_principal_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Principal Account',
                'verbose_name_plural': 'Principal Accounts',
                'db_table': 'principal_account',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date'], name='principal_a_date_471621_idx'), models.Index(fields=['source_module'], name='principal_a_source__c631a7_idx'), models.Index(fields=['type'], name='principal_a_type_8412c7_idx'), models.Index(fields=['source_id'], name='principal_a_source__326045_idx'), models.Index(fields=['is_active'], name='principal_a_is_acti_3ec31e_idx')],
            },
        ),
    ]
