# Generated by Django 6.0.1 on 2026-01-13 08:48

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], help_text='Type of period for this calculation', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the period')),
                ('end_date', models.DateField(help_text='End date of the period')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sales revenue', max_digits=15)),
                ('sales_count', models.PositiveIntegerField(default=0, help_text='Number of sales transactions')),
                ('average_sale_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average sale value', max_digits=15)),
                ('new_customers', models.PositiveIntegerField(default=0, help_text='Number of new customers')),
                ('returning_customers', models.PositiveIntegerField(default=0, help_text='Number of returning customers')),
                ('total_customers', models.PositiveIntegerField(default=0, help_text='Total unique customers')),
                ('products_sold', models.PositiveIntegerField(default=0, help_text='Total products sold')),
                ('top_selling_products', models.JSONField(default=list, help_text='List of top selling products with quantities')),
                ('low_stock_products', models.PositiveIntegerField(default=0, help_text='Number of products with low stock')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue from all sources', max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total expenses', max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net profit (revenue - expenses)', max_digits=15)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit margin percentage', max_digits=5)),
                ('orders_fulfilled', models.PositiveIntegerField(default=0, help_text='Number of orders fulfilled')),
                ('orders_pending', models.PositiveIntegerField(default=0, help_text='Number of pending orders')),
                ('average_fulfillment_time', models.PositiveIntegerField(default=0, help_text='Average order fulfillment time in days')),
                ('cash_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cash payments received', max_digits=15)),
                ('bank_transfers', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total bank transfers received', max_digits=15)),
                ('pending_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total pending payments', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Metrics',
                'verbose_name_plural': 'Business Metrics',
                'db_table': 'business_metrics',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInsights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(help_text='Customer identifier', max_length=100)),
                ('customer_name', models.CharField(help_text='Customer name', max_length=200)),
                ('total_purchases', models.PositiveIntegerField(default=0, help_text='Total number of purchases')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount spent', max_digits=15)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average order value', max_digits=15)),
                ('first_purchase_date', models.DateField(blank=True, help_text='Date of first purchase', null=True)),
                ('last_purchase_date', models.DateField(blank=True, help_text='Date of last purchase', null=True)),
                ('days_since_last_purchase', models.PositiveIntegerField(default=0, help_text='Days since last purchase')),
                ('customer_segment', models.CharField(blank=True, help_text='Customer segment (VIP, Regular, Occasional)', max_length=50)),
                ('loyalty_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer loyalty score (0-100)', max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Insights',
                'verbose_name_plural': 'Customer Insights',
                'db_table': 'customer_insights',
                'ordering': ['-total_spent'],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(help_text='Product identifier', max_length=100)),
                ('product_name', models.CharField(help_text='Product name', max_length=200)),
                ('category', models.CharField(blank=True, help_text='Product category', max_length=100)),
                ('units_sold', models.PositiveIntegerField(default=0, help_text='Total units sold')),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue generated', max_digits=15)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Product profit margin percentage', max_digits=5)),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Current stock level')),
                ('reorder_point', models.PositiveIntegerField(default=0, help_text='Reorder point for this product')),
                ('stock_turnover_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock turnover rate', max_digits=5)),
                ('is_top_seller', models.BooleanField(default=False, help_text='Whether this is a top selling product')),
                ('is_low_stock', models.BooleanField(default=False, help_text='Whether this product has low stock')),
                ('performance_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overall performance score (0-100)', max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Performance',
                'verbose_name_plural': 'Product Performance',
                'db_table': 'product_performance',
                'ordering': ['-revenue_generated'],
            },
        ),
    ]
