# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmetrics',
            name='calculated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customerinsights',
            index=models.Index(fields=['customer_segment'], name='customer_in_custome_913391_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinsights',
            index=models.Index(fields=['loyalty_score'], name='customer_in_loyalty_cc0860_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinsights',
            index=models.Index(fields=['last_purchase_date'], name='customer_in_last_pu_956c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='productperformance',
            index=models.Index(fields=['category'], name='product_per_categor_554098_idx'),
        ),
        migrations.AddIndex(
            model_name='productperformance',
            index=models.Index(fields=['is_top_seller'], name='product_per_is_top__e298bb_idx'),
        ),
        migrations.AddIndex(
            model_name='productperformance',
            index=models.Index(fields=['performance_score'], name='product_per_perform_53764f_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetrics',
            index=models.Index(fields=['period_type', 'start_date'], name='business_me_period__52b43a_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetrics',
            index=models.Index(fields=['start_date', 'end_date'], name='business_me_start_d_85d46a_idx'),
        ),
    ]
