# Generated by Django 6.0.1 on 2026-01-13 08:48

import advance_payments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labor_name', models.CharField(help_text='Cached labor name at time of payment', max_length=200)),
                ('labor_phone', models.CharField(help_text='Cached labor phone at time of payment', max_length=20)),
                ('labor_role', models.CharField(help_text='Cached labor designation/role at time of payment', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Advance amount given to labor', max_digits=10, validators=[advance_payments.models.validate_advance_amount])),
                ('description', models.TextField(blank=True, help_text='Purpose or description of the advance payment')),
                ('date', models.DateField(help_text='Date when advance payment was made', validators=[advance_payments.models.validate_payment_date])),
                ('time', models.TimeField(help_text='Time when advance payment was made')),
                ('receipt_image_path', models.ImageField(blank=True, help_text='Receipt image for the advance payment', null=True, upload_to=advance_payments.models.advance_payment_upload_path)),
                ('remaining_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining salary after this advance', max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, help_text="Labor's total monthly salary at time of payment", max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advance Payment',
                'verbose_name_plural': 'Advance Payments',
                'db_table': 'advance_payment',
                'ordering': ['-date', '-time', '-created_at'],
            },
        ),
    ]
