# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advance_payments', '0001_initial'),
        ('labors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advance_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='labor',
            field=models.ForeignKey(help_text='Labor receiving the advance payment', on_delete=django.db.models.deletion.PROTECT, related_name='advance_payments', to='labors.labor'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['labor'], name='advance_pay_labor_i_cd89f6_idx'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['labor_name'], name='advance_pay_labor_n_4763c8_idx'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['labor_phone'], name='advance_pay_labor_p_0cef49_idx'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['labor_role'], name='advance_pay_labor_r_dca472_idx'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['date'], name='advance_pay_date_98db74_idx'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['amount'], name='advance_pay_amount_832771_idx'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['is_active'], name='advance_pay_is_acti_0c1d77_idx'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['created_at'], name='advance_pay_created_d61ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['-date', '-time'], name='advance_pay_date_8b9beb_idx'),
        ),
    ]
