# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payables', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payable',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Link to vendor if creditor is a registered vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='payablepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payablepayment',
            name='payable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payables.payable'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['creditor_name'], name='payable_credito_d97fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['status'], name='payable_status_cd1b61_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['priority'], name='payable_priorit_9f5723_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['is_fully_paid'], name='payable_is_full_26a6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['expected_repayment_date'], name='payable_expecte_6966d8_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['date_borrowed'], name='payable_date_bo_cea8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['is_active'], name='payable_is_acti_1948ad_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['created_at'], name='payable_created_9e902e_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['vendor'], name='payable_vendor__19838d_idx'),
        ),
        migrations.AddIndex(
            model_name='payablepayment',
            index=models.Index(fields=['payable'], name='payable_pay_payable_a853a3_idx'),
        ),
        migrations.AddIndex(
            model_name='payablepayment',
            index=models.Index(fields=['payment_date'], name='payable_pay_payment_bbf3db_idx'),
        ),
        migrations.AddIndex(
            model_name='payablepayment',
            index=models.Index(fields=['created_at'], name='payable_pay_created_912a93_idx'),
        ),
    ]
