# Generated by Django 6.0.1 on 2026-01-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0002_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='purchase',
            field=models.OneToOneField(blank=True, help_text='Linked purchase if payable originated from a purchase', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payable', to='purchases.purchase'),
        ),
    ]
