# Generated by Django 6.0.2 on 2026-02-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cnic',
            field=models.CharField(blank=True, help_text='Customer CNIC number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='father_name',
            field=models.CharField(blank=True, help_text="Customer father's name", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Customer WhatsApp number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business name (for business customers)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Tax/NTN number (for business customers)', max_length=50, null=True),
        ),
    ]
