# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.core.validators
import labors.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the labor', max_length=200)),
                ('cnic', models.CharField(help_text='Pakistani CNIC in format: 12345-1234567-1', max_length=15, unique=True, validators=[labors.models.validate_pakistani_cnic])),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in valid format', regex='^[\\+]?[0-9\\-\\s]{10,20}$')])),
                ('caste', models.CharField(help_text='Caste/community of the labor', max_length=100)),
                ('designation', models.CharField(help_text='Job designation/position', max_length=150)),
                ('joining_date', models.DateField(help_text='Date when labor joined', validators=[labors.models.validate_joining_date])),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly salary amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_monthly_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining salary balance for current month (resets monthly)', max_digits=10)),
                ('current_month', models.PositiveIntegerField(default=0, help_text='Current month number (1-12) for tracking monthly resets')),
                ('current_year', models.PositiveIntegerField(default=0, help_text='Current year for tracking monthly resets')),
                ('area', models.CharField(help_text='Area/locality within the city', max_length=100)),
                ('city', models.CharField(help_text='City where labor is located', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender of the labor', max_length=1)),
                ('age', models.PositiveIntegerField(help_text='Age of the labor', validators=[django.core.validators.MinValueValidator(16, 'Minimum age must be 16 years'), django.core.validators.MaxValueValidator(70, 'Maximum age must be 70 years')])),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labors',
                'db_table': 'labor',
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
