# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_labors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['name'], name='labor_name_1e3af0_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['cnic'], name='labor_cnic_176622_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['phone_number'], name='labor_phone_n_e96671_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['designation'], name='labor_designa_91103f_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['caste'], name='labor_caste_bec34e_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['city'], name='labor_city_db5ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['area'], name='labor_area_f7c086_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['gender'], name='labor_gender_8a0722_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['joining_date'], name='labor_joining_8c3df9_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['salary'], name='labor_salary_a16daf_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['is_active'], name='labor_is_acti_3fd9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['created_at'], name='labor_created_6295e2_idx'),
        ),
    ]
