# Generated by Django 6.0.1 on 2026-01-13 08:48

import datetime
import django.db.models.deletion
import django.utils.timezone
import sales.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tax rate name (e.g., Standard GST, Reduced GST, FED on Textiles)', max_length=100)),
                ('tax_type', models.CharField(choices=[('GST', 'General Sales Tax'), ('FED', 'Federal Excise Duty'), ('WHT', 'Withholding Tax'), ('ADDITIONAL', 'Additional Tax'), ('CUSTOM', 'Custom Tax Rate')], default='GST', help_text='Type of tax', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Tax rate percentage (e.g., 17.00 for 17%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tax rate is currently active')),
                ('description', models.TextField(blank=True, help_text='Description of when this tax rate applies')),
                ('effective_from', models.DateField(default=datetime.date.today, help_text='Date from which this tax rate is effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this tax rate is effective (null for indefinite)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'db_table': 'tax_rates',
                'ordering': ['tax_type', 'effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(default=sales.models.generate_invoice_number, help_text='Auto-generated invoice number', max_length=20, unique=True)),
                ('customer_name', models.CharField(help_text='Cached customer name at time of sale', max_length=200)),
                ('customer_phone', models.CharField(help_text='Cached customer contact at time of sale', max_length=20)),
                ('customer_email', models.EmailField(blank=True, help_text='Cached customer email at time of sale', max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line items before discounts', max_digits=15)),
                ('overall_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount applied to entire sale', max_digits=12)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('17.00'), help_text='GST tax rate (default 17% for Pakistan)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated GST amount', max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final amount after discounts and taxes', max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount received from customer', max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance', max_digits=15)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Payment completion status')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_PAYMENT', 'Mobile Payment (JazzCash/EasyPaisa)'), ('SPLIT', 'Split Payment'), ('CREDIT', 'Credit Sale')], default='CASH', help_text='Method of payment', max_length=20)),
                ('split_payment_details', models.JSONField(blank=True, default=dict, help_text="Details for multiple payment methods when payment_method='Split'")),
                ('date_of_sale', models.DateTimeField(default=django.utils.timezone.now, help_text='Transaction timestamp')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='DRAFT', help_text='Current sale status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional sale information or special instructions')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Sales person who processed the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer making the purchase', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
                ('order_id', models.ForeignKey(blank=True, help_text='Optional: Order this sale was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.order')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
                'ordering': ['-date_of_sale', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_item', models.UUIDField(blank=True, help_text='Optional: Order item ID this sale item was created from', null=True)),
                ('product_name', models.CharField(help_text='Cached product name at time of sale', max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit at time of sale', max_digits=12)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units sold')),
                ('item_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied to this specific item', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for this line after discount', max_digits=15)),
                ('customization_notes', models.TextField(blank=True, help_text='Inherited from order item or new customizations')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Sold product reference', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(help_text='Parent sale transaction', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sales.sales')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'db_table': 'sale_item',
                'ordering': ['sale', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(help_text='Unique return number', max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item Received'), ('DAMAGED', 'Damaged in Transit'), ('SIZE_ISSUE', 'Size/Fit Issue'), ('QUALITY_ISSUE', 'Quality Issue'), ('CUSTOMER_REQUEST', 'Customer Request'), ('OTHER', 'Other')], help_text='Primary reason for return', max_length=20)),
                ('reason_details', models.TextField(blank=True, help_text='Detailed explanation of return reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of return request', max_length=20)),
                ('return_date', models.DateTimeField(auto_now_add=True, help_text='When return was requested')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When return was approved', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When return was processed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the return')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be refunded', max_digits=10, null=True)),
                ('refund_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CREDIT_NOTE', 'Credit Note'), ('EXCHANGE', 'Exchange'), ('OTHER', 'Other')], help_text='Method of refund', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this return request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer requesting the return', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='customers.customer')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(help_text='Original sale for this return', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sales')),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'db_table': 'sales_return',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(help_text='Unique receipt number', max_length=20, unique=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When receipt was generated')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent to Customer'), ('VIEWED', 'Viewed by Customer'), ('ARCHIVED', 'Archived')], default='GENERATED', help_text='Current receipt status', max_length=20)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF receipt file', null=True, upload_to='receipts/')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether receipt was emailed to customer')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When receipt was last emailed', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When customer last viewed the receipt', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional receipt notes')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who generated this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(help_text='Associated payment', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.payment')),
                ('sale', models.ForeignKey(help_text='Associated sale', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='sales.sales')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'sales_receipt',
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=20, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time invoice was issued')),
                ('due_date', models.DateTimeField(blank=True, help_text='Payment due date (optional)', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('SENT', 'Sent to Customer'), ('VIEWED', 'Viewed by Customer'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current invoice status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional invoice notes')),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions for this invoice')),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF invoice file', null=True, upload_to='invoices/')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether invoice was emailed to customer')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When invoice was last emailed', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When customer last viewed the invoice', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(help_text='Associated sale', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.sales')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'sales_invoice',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(help_text='Unique refund number', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be refunded', max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CREDIT_NOTE', 'Credit Note'), ('OTHER', 'Other')], help_text='Refund method', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of refund', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='External reference number (check number, transfer ID, etc.)', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When refund was processed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the refund')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(help_text='Return request this refund is for', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.return')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'sales_refund',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['refund_number'], name='sales_refun_refund__7be765_idx'), models.Index(fields=['return_request'], name='sales_refun_return__3f731b_idx'), models.Index(fields=['status'], name='sales_refun_status_e522ec_idx'), models.Index(fields=['method'], name='sales_refun_method_972077_idx'), models.Index(fields=['is_active'], name='sales_refun_is_acti_05debe_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_returned', models.PositiveIntegerField(help_text='Quantity being returned')),
                ('return_amount', models.DecimalField(decimal_places=2, help_text='Amount to be returned for this item', max_digits=10)),
                ('return_reason', models.CharField(blank=True, help_text='Specific reason for returning this item', max_length=100)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', help_text='Condition of returned item', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this item')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_request', models.ForeignKey(help_text='Return request this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='sales.return')),
                ('sale_item', models.ForeignKey(help_text='Original sale item being returned', on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='sales.saleitem')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'db_table': 'sales_return_item',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['return_request'], name='sales_retur_return__09a9b1_idx'), models.Index(fields=['sale_item'], name='sales_retur_sale_it_7d1c55_idx'), models.Index(fields=['is_active'], name='sales_retur_is_acti_c724c6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['invoice_number'], name='sales_invoice_248678_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['customer'], name='sales_custome_acc50a_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['order_id'], name='sales_order_i_ca9be9_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['status'], name='sales_status_a83c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['payment_method'], name='sales_payment_541ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['date_of_sale'], name='sales_date_of_58a83c_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['is_fully_paid'], name='sales_is_full_70f390_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['is_active'], name='sales_is_acti_915e45_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['created_at'], name='sales_created_dbdf91_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='sale_item_sale_id_4a18e9_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['order_item'], name='sale_item_order_i_e66f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='sale_item_product_239bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['is_active'], name='sale_item_is_acti_b84543_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['created_at'], name='sale_item_created_6ec332_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_number'], name='sales_retur_return__4abfa6_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['sale'], name='sales_retur_sale_id_d5b460_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['customer'], name='sales_retur_custome_4a565b_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status'], name='sales_retur_status_6097bb_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_date'], name='sales_retur_return__9201ce_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['is_active'], name='sales_retur_is_acti_d81c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='sales_recei_receipt_0e369b_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['sale'], name='sales_recei_sale_id_1567f1_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment'], name='sales_recei_payment_f75fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status'], name='sales_recei_status_fe434f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['generated_at'], name='sales_recei_generat_9847c4_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['is_active'], name='sales_recei_is_acti_a0e2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='sales_invoi_invoice_51f3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sale'], name='sales_invoi_sale_id_470fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='sales_invoi_status_4e3758_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='sales_invoi_issue_d_0a58aa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='sales_invoi_due_dat_a262a4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_active'], name='sales_invoi_is_acti_615ff3_idx'),
        ),
    ]
