# Generated by Django 6.0.1 on 2026-01-18 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('orders', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['date_of_sale', '-created_at'], name='sales_date_of_b97643_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['status', 'is_active'], name='sales_status_085905_idx'),
        ),
    ]
