# Generated by Django 6.0.1 on 2026-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_sales_date_of_b97643_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='tax_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible tax configuration as JSON'),
        ),
    ]
