# Generated by Django 6.0.1 on 2026-01-24 22:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('sales', '0003_sales_tax_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer making the purchase (optional for walk-in sales)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(default='Walk-in Customer', help_text='Cached customer name at time of sale', max_length=200),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_phone',
            field=models.CharField(blank=True, default='', help_text='Cached customer contact at time of sale', max_length=20),
        ),
        migrations.AlterField(
            model_name='sales',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST tax rate (default 17% for Pakistan)', max_digits=5),
        ),
    ]
