# Generated by Django 6.0.1 on 2026-01-26 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('sales', '0004_alter_sales_customer_alter_sales_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer requesting the return', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='customers.customer'),
        ),
    ]
