# Generated by Django 6.0.1 on 2026-01-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_return_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item Received'), ('WRONG_COLOR', 'Wrong Color'), ('DAMAGED', 'Damaged in Transit'), ('SIZE_ISSUE', 'Size/Fit Issue'), ('QUALITY_ISSUE', 'Quality Issue'), ('CUSTOMER_REQUEST', 'Customer Request'), ('OTHER', 'Other')], help_text='Primary reason for return', max_length=20),
        ),
    ]
