# Generated by Django 6.0.1 on 2026-01-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('WRONG_SIZE', 'Wrong Size'), ('WRONG_COLOR', 'Wrong Color'), ('QUALITY_ISSUE', 'Quality Issue'), ('CUSTOMER_CHANGE_MIND', 'Customer Changed Mind'), ('DAMAGED_IN_TRANSIT', 'Damaged in Transit'), ('OTHER', 'Other')], help_text='Primary reason for return', max_length=20),
        ),
    ]
