# Generated by Django 6.0.1 on 2026-01-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New/Unused'), ('GOOD', 'Good Condition'), ('FAIR', 'Fair Condition'), ('POOR', 'Poor Condition'), ('DAMAGED', 'Damaged')], default='GOOD', help_text='Condition of returned item', max_length=20),
        ),
    ]
