# Generated by Django 6.0.1 on 2026-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_returnitem_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('SIZE_ISSUE', 'Wrong Size'), ('WRONG_COLOR', 'Wrong Color'), ('QUALITY_ISSUE', 'Quality Issue'), ('CUSTOMER_REQUEST', 'Customer Changed Mind'), ('DAMAGED', 'Damaged'), ('OTHER', 'Other')], help_text='Primary reason for return', max_length=20),
        ),
    ]
