# Generated by Django 6.0.1 on 2026-01-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payable'),
        ('sales', '0009_alter_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Associated payment (optional for simple receipts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.payment'),
        ),
    ]
