# Generated by Django 6.0.2 on 2026-02-28 07:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='quantity_returned',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity being returned', max_digits=12),
        ),
    ]
