# Generated by Django 6.0.2 on 2026-02-05 20:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense', models.CharField(help_text='Expense title/name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the expense')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('withdrawal_by', models.CharField(help_text='Who authorized/made the withdrawal', max_length=100)),
                ('date', models.DateField(help_text='Date of expense')),
                ('time', models.TimeField(help_text='Time of expense')),
                ('category', models.CharField(blank=True, help_text='Optional expense category', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='For soft deletion')),
                ('is_personal', models.BooleanField(default=False, help_text='Whether this is a personal expense')),
                ('created_by', models.ForeignKey(help_text='Who recorded this expense', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expense',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date'], name='expense_date_983134_idx'), models.Index(fields=['withdrawal_by'], name='expense_withdra_7c54bf_idx'), models.Index(fields=['category'], name='expense_categor_3e67c8_idx'), models.Index(fields=['is_active'], name='expense_is_acti_6d2512_idx'), models.Index(fields=['created_at'], name='expense_created_0a6070_idx')],
            },
        ),
    ]
