# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.core.validators
import django.db.models.deletion
import uuid
import vendors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the vendor', max_length=200)),
                ('business_name', models.CharField(help_text='Name of the business/company', max_length=200)),
                ('cnic', models.CharField(help_text='Pakistani CNIC in format: 12345-1234567-1', max_length=15, unique=True, validators=[vendors.models.validate_pakistani_cnic])),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in valid format', regex='^[\\+]?[0-9\\-\\s]{10,20}$')])),
                ('city', models.CharField(help_text='City where vendor is located', max_length=100)),
                ('area', models.CharField(help_text='Area/locality within the city', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendor',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['name'], name='vendor_name_3e8102_idx'), models.Index(fields=['business_name'], name='vendor_busines_ddb33f_idx'), models.Index(fields=['cnic'], name='vendor_cnic_23fb15_idx'), models.Index(fields=['phone'], name='vendor_phone_bd7ea0_idx'), models.Index(fields=['city'], name='vendor_city_9bc7b4_idx'), models.Index(fields=['area'], name='vendor_area_b8e961_idx'), models.Index(fields=['is_active'], name='vendor_is_acti_aca0de_idx'), models.Index(fields=['created_at'], name='vendor_created_0bd09d_idx')],
            },
        ),
    ]
