# Generated by Django 6.0.2 on 2026-02-27 01:31

import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_update_cnic_to_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='cnic',
            field=models.CharField(blank=True, help_text='Pakistani CNIC in format: 12345-1234567-1 (optional)', max_length=15, null=True, unique=True, validators=[vendors.models.validate_pakistani_cnic]),
        ),
    ]
