# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.core.validators
import payments.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_type', models.CharField(choices=[('LABOR', 'Labor'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer'), ('OTHER', 'Other')], help_text='Type of entity making the payment', max_length=20)),
                ('payer_id', models.UUIDField(blank=True, help_text='ID of the payer entity', null=True)),
                ('labor_name', models.CharField(blank=True, help_text='Cached labor name at time of payment', max_length=200)),
                ('labor_phone', models.CharField(blank=True, help_text='Cached labor phone at time of payment', max_length=20)),
                ('labor_role', models.CharField(blank=True, help_text='Cached labor role at time of payment', max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonus amount (if any)', max_digits=10)),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deduction amount (if any)', max_digits=10)),
                ('payment_month', models.DateField(help_text='Month for which payment is made')),
                ('is_final_payment', models.BooleanField(default=False, help_text='Whether this is the final payment for the period')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_PAYMENT', 'Mobile Payment (JazzCash/EasyPaisa)'), ('CHECK', 'Check'), ('CARD', 'Credit/Debit Card'), ('OTHER', 'Other')], default='CASH', help_text='Method of payment', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Payment description and notes')),
                ('date', models.DateField(help_text='Date of payment', validators=[payments.models.validate_payment_date])),
                ('time', models.TimeField(help_text='Time of payment')),
                ('receipt_image_path', models.FileField(blank=True, help_text='Receipt file for payment verification (JPG, PNG, PDF, max 5MB)', null=True, upload_to=payments.models.payment_receipt_upload_path, validators=[payments.models.validate_receipt_file_size])),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
                'ordering': ['-date', '-time', '-created_at'],
            },
        ),
    ]
