# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('labors', '0002_initial'),
        ('orders', '0002_initial'),
        ('payments', '0001_initial'),
        ('sales', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='labor',
            field=models.ForeignKey(blank=True, help_text='Labor receiving payment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='labors.labor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order this payment is related to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Sale this payment is related to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.sales'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor receiving payment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['labor'], name='payment_labor_i_b1e6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['vendor'], name='payment_vendor__3df712_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payment_order_i_f08ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale'], name='payment_sale_id_745f50_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer_type'], name='payment_payer_t_ce6651_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_month'], name='payment_payment_27d619_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='payment_date_9bceae_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payment_payment_d8e241_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_final_payment'], name='payment_is_fina_0dbe70_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_active'], name='payment_is_acti_f29160_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payment_created_6be7be_idx'),
        ),
    ]
