# Generated by Django 6.0.1 on 2026-01-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0003_payable_purchase'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payable',
            field=models.ForeignKey(blank=True, help_text='Payable this payment is reducing (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_payments', to='payables.payable'),
        ),
    ]
