# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Zakat payment/distribution title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the Zakat transaction')),
                ('date', models.DateField(help_text='Date of Zakat transaction')),
                ('time', models.TimeField(help_text='Time of Zakat transaction')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Zakat amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('beneficiary_name', models.CharField(help_text='Name of recipient/beneficiary', max_length=200)),
                ('beneficiary_contact', models.CharField(blank=True, help_text='Optional contact number', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or religious considerations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.CharField(choices=[('Mr. Shahzain Baloch', 'Mr. Shahzain Baloch'), ('Mr Huzaifa', 'Mr Huzaifa')], help_text='Who authorized the Zakat payment', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='For soft deletion')),
                ('created_by', models.ForeignKey(help_text='Who recorded this Zakat entry', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zakat',
                'verbose_name_plural': 'Zakat Entries',
                'db_table': 'zakat',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date'], name='zakat_date_59b8eb_idx'), models.Index(fields=['authorized_by'], name='zakat_authori_940775_idx'), models.Index(fields=['beneficiary_name'], name='zakat_benefic_2f7421_idx'), models.Index(fields=['is_active'], name='zakat_is_acti_4bbd85_idx'), models.Index(fields=['created_at'], name='zakat_created_777107_idx')],
            },
        ),
    ]
