# Generated by Django 6.0.1 on 2026-01-13 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Cached product name at time of order', max_length=200)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of this product ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of order (cached from product)', max_digits=12)),
                ('customization_notes', models.TextField(blank=True, help_text='Special instructions or customization notes for this item')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Calculated total for this line item', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_item',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
