# Generated by Django 6.0.2 on 2026-02-27 07:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity of this product ordered (supports decimal weights like KG)', max_digits=12),
        ),
    ]
